language: java

before_install:
 - chmod +x mvnw

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk11
    - os: linux
      dist: xenial
      jdk: oraclejdk11
    - os: linux
      dist: trusty
      jdk: openjdk11
# TODO openjfx is not supported on trusty, need alternatives
#    - os: linux
#      dist: trusty
#      jdk: openjdk8
#      addons: {apt: {packages: [openjfx]}}
    - os: osx
      osx_image: xcode8.3

sudo: false

script:
 - ./mvnw install -Prelease -DskipTests=true -B -V
 - ./mvnw test
 - ./mvnw clean package -DskipTests=true
